name: Build & Push Docker Image – Produits API

on:
  push:
    branches: ["*"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        run: |
          IMAGE=ghcr.io/mgaisnon/mspr-api-produits
          docker build -t $IMAGE:latest .
          docker push $IMAGE:latest
